/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funciones.MostrarAntepasados;
import static Interfaces.Welcome.gestionApp;
import static Interfaces.Welcome.validar;
import Principal.Persona;
import javax.swing.JOptionPane;

/**
 *
 * @author samantha
 */
public class Antepasados extends javax.swing.JFrame {

    private Persona[] resultados;
    /**
     * Creates new form MostrarAntepasados
     */
    public Antepasados() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        resultadoStr = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        inputIndice = new javax.swing.JTextField();
        verAntepasados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("MOSTRAR ANTEPASADOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        exit.setBackground(new java.awt.Color(204, 204, 204));
        exit.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 40, -1));

        volver.setBackground(new java.awt.Color(204, 204, 204));
        volver.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        volver.setText("<-- Volver al menú");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Ingresa el nombre de la persona:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 30));

        inputNombre.setBackground(new java.awt.Color(204, 204, 204));
        inputNombre.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        jPanel1.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 240, -1));

        buscar.setBackground(new java.awt.Color(204, 204, 204));
        buscar.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 80, -1));

        resultadoStr.setBackground(new java.awt.Color(204, 204, 204));
        resultadoStr.setColumns(20);
        resultadoStr.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        resultadoStr.setRows(5);
        jPanel1.add(resultadoStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Ingrese el indice de la persona para mostrar los antepasados:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        inputIndice.setBackground(new java.awt.Color(204, 204, 204));
        inputIndice.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        jPanel1.add(inputIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 180, -1));

        verAntepasados.setBackground(new java.awt.Color(204, 204, 204));
        verAntepasados.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        verAntepasados.setText("Ver Antepasados");
        verAntepasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAntepasadosActionPerformed(evt);
            }
        });
        jPanel1.add(verAntepasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String nombreBusq = inputNombre.getText();
        resultados = gestionApp.buscarSoloNombre(nombreBusq);
        if (resultados != null) {

            resultadoStr.setText(gestionApp.mostrarBusquedaSoloNombre(resultados));
        } else {
            resultadoStr.setText("");
            JOptionPane.showMessageDialog(null, "No se encontraron coincidencias con la busqueda.");
        }

    }//GEN-LAST:event_buscarActionPerformed

    private void verAntepasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAntepasadosActionPerformed
        String indiceStr = inputIndice.getText();
        if (validar.convertirNumero(indiceStr) != -1) {
            int index = validar.convertirNumero(indiceStr);
            if (validar.validarIndice(resultados.length, index)) {
                System.setProperty("org.graphstream.ui", "swing");

                MostrarAntepasados verArbol = new MostrarAntepasados(gestionApp.antepasados(resultados[index]), this);
                verArbol.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Indice Invalido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe ser un numero entero");
        }
        inputIndice.setText("");
    }//GEN-LAST:event_verAntepasadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Antepasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Antepasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Antepasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Antepasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Antepasados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton exit;
    private javax.swing.JTextField inputIndice;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea resultadoStr;
    private javax.swing.JButton verAntepasados;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
