/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.TablaHash;
import Funciones.MostrarDescendencia;
import static Interfaces.Welcome.gestionApp;
import static Interfaces.Welcome.validar;
import Principal.Persona;
import javax.swing.JOptionPane;


/**
 *
 * @author samantha
 */
public class BuscarPorNombre extends javax.swing.JFrame {

    private Persona[] resultados;
    /**
     * Creates new form BuscarPorNombre
     */
    public BuscarPorNombre() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarNombres = new javax.swing.JTextArea();
        inputIndice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buscarNombre = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        verDescendencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputNombre.setBackground(new java.awt.Color(204, 204, 204));
        inputNombre.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });
        jPanel1.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 270, -1));

        jLabel1.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("BUSCAR POR NOMBRE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        exit.setBackground(new java.awt.Color(204, 204, 204));
        exit.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 40, -1));

        jLabel2.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Ingrese el indice de la persona para mostrar la descendencia:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        mostrarNombres.setBackground(new java.awt.Color(204, 204, 204));
        mostrarNombres.setColumns(20);
        mostrarNombres.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        mostrarNombres.setRows(5);
        jScrollPane1.setViewportView(mostrarNombres);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 270, 140));

        inputIndice.setBackground(new java.awt.Color(204, 204, 204));
        inputIndice.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inputIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIndiceActionPerformed(evt);
            }
        });
        jPanel1.add(inputIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 130, -1));

        jLabel3.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Ingresa el nombre que quieres buscar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        buscarNombre.setBackground(new java.awt.Color(204, 204, 204));
        buscarNombre.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        buscarNombre.setText("Buscar");
        buscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNombreActionPerformed(evt);
            }
        });
        jPanel1.add(buscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        volver.setBackground(new java.awt.Color(204, 204, 204));
        volver.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        volver.setText("<-- Volver al menú");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        verDescendencia.setBackground(new java.awt.Color(204, 204, 204));
        verDescendencia.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        verDescendencia.setText("Ver descendencia");
        verDescendencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDescendenciaActionPerformed(evt);
            }
        });
        jPanel1.add(verDescendencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void buscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNombreActionPerformed
 String nombreBusq = inputNombre.getText();
        resultados = gestionApp.buscarNombre(nombreBusq);
        if (resultados != null) {
            
            mostrarNombres.setText(gestionApp.mostrarBusquedaNombre(resultados));
        } else {
            mostrarNombres.setText("");
            JOptionPane.showMessageDialog(null, "No se encontraron coincidencias con la busqueda.");
        }
               
       
        
    }//GEN-LAST:event_buscarNombreActionPerformed

    private void inputIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIndiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIndiceActionPerformed

    private void verDescendenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDescendenciaActionPerformed
        String indiceStr = inputIndice.getText();
        if (validar.convertirNumero(indiceStr) != -1) {
            int index = validar.convertirNumero(indiceStr);
            if (validar.validarIndice(resultados.length, index)) {
                System.setProperty("org.graphstream.ui", "swing");
                
                MostrarDescendencia verArbol = new MostrarDescendencia(gestionApp.descendencia(resultados[index]), this);
                verArbol.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Indice Invalido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe ser un numero entero");
        }
        inputIndice.setText("");
    }//GEN-LAST:event_verDescendenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPorNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPorNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPorNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPorNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarPorNombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarNombre;
    private javax.swing.JButton exit;
    private javax.swing.JTextField inputIndice;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mostrarNombres;
    private javax.swing.JButton verDescendencia;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
