/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import static Interfaces.Welcome.gestionApp;
import Principal.Persona;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author samantha
 */
public class Generacion extends javax.swing.JFrame {
    DefaultComboBoxModel modeloGeneracion = new DefaultComboBoxModel();
    private Persona[] resultados = null;
    
    public Generacion() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.llenarGeneracios();
    }
    
    private void llenarGeneracios(){
        for (int i = 0; i < gestionApp.generacionesDispo().getSize(); i++) {
            modeloGeneracion.addElement(gestionApp.generacionesDispo().getValor(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        generacionesDisponibles = new javax.swing.JComboBox<>();
        listarGen = new javax.swing.JButton();
        resultadoStr = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("GENERACIONES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        exit.setBackground(new java.awt.Color(204, 204, 204));
        exit.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 40, -1));

        volver.setBackground(new java.awt.Color(204, 204, 204));
        volver.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        volver.setText("<-- Volver al menú");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Selecciona la generacion que quieres mostrar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        generacionesDisponibles.setBackground(new java.awt.Color(204, 204, 204));
        generacionesDisponibles.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        generacionesDisponibles.setModel(modeloGeneracion);
        generacionesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generacionesDisponiblesActionPerformed(evt);
            }
        });
        jPanel1.add(generacionesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 240, -1));

        listarGen.setBackground(new java.awt.Color(204, 204, 204));
        listarGen.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        listarGen.setText("Listar Generacion");
        listarGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarGenActionPerformed(evt);
            }
        });
        jPanel1.add(listarGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        resultadoStr.setBackground(new java.awt.Color(204, 204, 204));
        resultadoStr.setColumns(20);
        resultadoStr.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        resultadoStr.setRows(5);
        jPanel1.add(resultadoStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 250, 180));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/generacion.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Menu menu = new Menu();
    }//GEN-LAST:event_volverActionPerformed

    private void generacionesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generacionesDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generacionesDisponiblesActionPerformed

    private void listarGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarGenActionPerformed
        int numGen = (int) generacionesDisponibles.getSelectedItem();
        resultados = gestionApp.buscarGeneracion(numGen);
        if(resultados==null){
            resultadoStr.setText("No se encontraron resultados\n");
        }else{
            resultadoStr.setText(gestionApp.mostrarGeneracion(resultados, numGen));
        }
    }//GEN-LAST:event_listarGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JComboBox<String> generacionesDisponibles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listarGen;
    private javax.swing.JTextArea resultadoStr;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
